name: Deploy docs to production

on:
  push:
    branches:
      - main

permissions:
  contents: read
  deployments: write
  id-token: write

env:
  SLUG: portals-android-api-ref

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    environment:
      name: production
      url: https://ionic.io/docs/${{ env.SLUG }}
    steps:
      - uses: actions/checkout@v2
      - name: create local.properties file for app creds
        run: echo portals_key=\"replace me with real key\" > ./local.properties
      - name: set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
      - name: Generate Docs
        run: ./gradlew dokkaHtml
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::319312831725:role/github-docs
          aws-region: us-east-1
      - name: Deploy
        run: |
          aws s3 sync IonicPortals/build/dokka/html/ s3://ionic-docs/production/${{ env.SLUG }}/ --exclude '*.html' --cache-control max-age=31536000 --only-show-errors
          aws s3 sync IonicPortals/build/dokka/html/ s3://ionic-docs/production/${{ env.SLUG }}/ --exclude '*' --include '*.html' --cache-control max-age=60 --only-show-errors