name: Run UI Tests

on: pull_request
jobs:
  test:
    runs-on: macos-latest
    strategy:
      matrix:
        api-level: [24, 33]
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: create local.properties file for app creds
        env:
          PORTALS_KEY: ${{ secrets.portals_key }}
        run: echo portals_key=\"$PORTALS_KEY\" > ./local.properties

      - name: set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Gradle cache
        uses: gradle/gradle-build-action@v2

      - name: AVD cache
        uses: actions/cache@v3
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-aosp-${{ matrix.api-level }}

      - name: create AVD and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: aosp_atd
          arch: x86_64
          channel: canary
          profile: pixel
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          script: echo "Generated AVD snapshot for caching."

      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: aosp_atd
          arch: x86_64
          channel: canary
          profile: pixel
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: ./gradlew connectedCheck